### PR TITLE
[263] add test cases for CustomShoppingListItemController

### PR DESCRIPTION
**Pull request by ushh789**
Added tests for CustomShoppingListItemController methods.
image

### CODE REVIEW

**Comment by IliaWithHat** [comment]
If you test "CustomShoppingListItemController" name the test class "CustomShoppingListItemControllerTest", not "CustomShoppingListControllerTest"

**Comment by ushh789** [comment]
> If you test "CustomShoppingListItemController" name the test class "CustomShoppingListItemControllerTest", not "CustomShoppingListControllerTest"

Thank you for your feedback. I've renamed the class and cleaned up the code. Could you review it again for approval?

**Comment by IliaWithHat** [comment]
> > If you test "CustomShoppingListItemController" name the test class "CustomShoppingListItemControllerTest", not "CustomShoppingListControllerTest"
> 
> Thank you for your feedback. I've renamed the class and cleaned up the code. Could you review it again for approval?

Instead of creating a new CustomShoppingListItemResponseDto instance in the setup() method, you can use the getCustomShoppingListItemResponseDto() method from the ModelUtils class. And there's no need to initialize this object before each method. Furthermore, I've noticed that deleting the tearDown() method didn't affect the test results, suggesting its unnecessary here.

**Review by IliaWithHat — APPROVED** [review]

**Comment by ushh789** [comment]
> > > If you test "CustomShoppingListItemController" name the test class "CustomShoppingListItemControllerTest", not "CustomShoppingListControllerTest"
> > 
> > 
> > Thank you for your feedback. I've renamed the class and cleaned up the code. Could you review it again for approval?
> 
> Instead of creating a new CustomShoppingListItemResponseDto instance in the setup() method, you can use the getCustomShoppingListItemResponseDto() method from the ModelUtils class. And there's no need to initialize this object before each method. Furthermore, I've noticed that deleting the tearDown() method didn't affect the test results, suggesting its unnecessary here.

Thanks for the review! I've implemented all the suggested changes.

**Review by tellmant — APPROVED** [review]

**Review by df7734 — APPROVED** [review]

**Pull request merged**
