### PR TITLE
[223] add test cases for HabitAssignController

### PR DESCRIPTION
**Pull request by tellmant**
Added test cases for HabitAssignController.

Controller covered by tests by 100%.
image

### CODE REVIEW

**Comment by IliaWithHat** [comment]
Why you create new ObjectMapper() before each method? And you dont need CustomArgumentResolvers, you can just write "mockMvc = MockMvcBuilders.standaloneSetup(habitAssignController).build();"

**Comment by tellmant** [comment]
> Why you create new ObjectMapper() before each method? And you dont need CustomArgumentResolvers, you can just write "mockMvc = MockMvcBuilders.standaloneSetup(habitAssignController).build();"

I removed redundant code in new commits, thanks for your review.

**Review by IliaWithHat — APPROVED** [review]

**Review by ushh789 — APPROVED** [review]

**Review by df7734 — COMMENTED** [review]
Not sure leaving nulls for userIds is a good practice

My suggestion:
final Long USER_ID = 131L;

[Inside mockMvc.perform]
.param("id", String.valueOf(USER_ID))

[Inside verify]
Put USER_ID  instead null

**Comment by tellmant** [comment]
> Not sure leaving nulls for userIds is a good practice
> 
> My suggestion: final Long USER_ID = 131L;
> 
> [Inside mockMvc.perform] .param("id", String.valueOf(USER_ID))
> 
> [Inside verify] Put USER_ID instead null

I refactored the null values in requests with UserVO by replacing them with the constant USER_ID. Thanks for your review!

**Review by df7734 — APPROVED** [review]

**Pull request merged**
