### PR TITLE
[261] add test cases for HabitFactController

### PR DESCRIPTION
**Pull request by IliaWithHat**

### CODE REVIEW

**Review by ushh789 — APPROVED** [review]
Everything is fine, but you may want to remove this field:
@Mock
private ModelMapper modelMapper;
(since it was not used)

**Comment by IliaWithHat** [comment]
> Everything is fine, but you may want to remove this field: @mock private ModelMapper modelMapper; (since it was not used)

ModelMapper is used in save and update methods, so if i remove it, i get "jakarta.servlet.ServletException: Request processing failed: java.lang.NullPointerException: Cannot invoke "org.modelmapper.ModelMapper.map(Object, java.lang.Class)" because "this.mapper" is null".

**Review by tellmant — COMMENTED** [review]
It would be great to use some test naming conventions, e.g. **MethodName_StateUnderTest_ExpectedBehaviour**. 

Also, remove any redundant code if possible: you are creating a variable of type **ObjectMapper**, but each time you use this class, you are creating a new instance with **new ObjectMapper()**. Either remove the variable or initialize it once. 

It's better practice to use **HabitFactService** interface instead of **HabitFactServiceImpl**

**Comment by IliaWithHat** [comment]
> It would be great to use some test naming conventions, e.g. **MethodName_StateUnderTest_ExpectedBehaviour**.
> 
> Also, remove any redundant code if possible: you are creating a variable of type **ObjectMapper**, but each time you use this class, you are creating a new instance with **new ObjectMapper()**. Either remove the variable or initialize it once.
> 
> It's better practice to use **HabitFactService** interface instead of **HabitFactServiceImpl**

Updated.

**Review by tellmant — APPROVED** [review]

**Review by df7734 — APPROVED** [review]

**Review by RockTF — APPROVED** [review]

**Pull request merged**
